#############################################################################
# Makefile for building: epoll
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  epoll.pro
# Template: app
# Command: /home/lzb/Qt5.5.1/5.5/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug -o Makefile epoll.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -pipe -g -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=c++0x -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../5.5/gcc_64/mkspecs/linux-g++
QMAKE         = /home/lzb/Qt5.5.1/5.5/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = epoll1.0.0
DISTDIR = /home/lzb/Qt5.5.1/qt_project/epoll/.tmp/epoll1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/lzb/Qt5.5.1/5.5/gcc_64
LIBS          = $(SUBLIBS)  
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp 
OBJECTS       = main.o
DIST          = ../../5.5/gcc_64/mkspecs/features/spec_pre.prf \
		../../5.5/gcc_64/mkspecs/common/unix.conf \
		../../5.5/gcc_64/mkspecs/common/linux.conf \
		../../5.5/gcc_64/mkspecs/common/sanitize.conf \
		../../5.5/gcc_64/mkspecs/common/gcc-base.conf \
		../../5.5/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../5.5/gcc_64/mkspecs/common/g++-base.conf \
		../../5.5/gcc_64/mkspecs/common/g++-unix.conf \
		../../5.5/gcc_64/mkspecs/qconfig.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_3dcollision.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_3dcollision_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../5.5/gcc_64/mkspecs/features/qt_functions.prf \
		../../5.5/gcc_64/mkspecs/features/qt_config.prf \
		../../5.5/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../5.5/gcc_64/mkspecs/features/spec_post.prf \
		../../5.5/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../5.5/gcc_64/mkspecs/features/default_pre.prf \
		../../5.5/gcc_64/mkspecs/features/resolve_config.prf \
		../../5.5/gcc_64/mkspecs/features/default_post.prf \
		../../5.5/gcc_64/mkspecs/features/c++11.prf \
		../../5.5/gcc_64/mkspecs/features/warn_on.prf \
		../../5.5/gcc_64/mkspecs/features/testcase_targets.prf \
		../../5.5/gcc_64/mkspecs/features/exceptions.prf \
		../../5.5/gcc_64/mkspecs/features/yacc.prf \
		../../5.5/gcc_64/mkspecs/features/lex.prf \
		epoll.pro  main.cpp
QMAKE_TARGET  = epoll
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = epoll


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: epoll.pro ../../5.5/gcc_64/mkspecs/linux-g++/qmake.conf ../../5.5/gcc_64/mkspecs/features/spec_pre.prf \
		../../5.5/gcc_64/mkspecs/common/unix.conf \
		../../5.5/gcc_64/mkspecs/common/linux.conf \
		../../5.5/gcc_64/mkspecs/common/sanitize.conf \
		../../5.5/gcc_64/mkspecs/common/gcc-base.conf \
		../../5.5/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../5.5/gcc_64/mkspecs/common/g++-base.conf \
		../../5.5/gcc_64/mkspecs/common/g++-unix.conf \
		../../5.5/gcc_64/mkspecs/qconfig.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_3dcollision.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_3dcollision_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../5.5/gcc_64/mkspecs/features/qt_functions.prf \
		../../5.5/gcc_64/mkspecs/features/qt_config.prf \
		../../5.5/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../5.5/gcc_64/mkspecs/features/spec_post.prf \
		../../5.5/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../5.5/gcc_64/mkspecs/features/default_pre.prf \
		../../5.5/gcc_64/mkspecs/features/resolve_config.prf \
		../../5.5/gcc_64/mkspecs/features/default_post.prf \
		../../5.5/gcc_64/mkspecs/features/c++11.prf \
		../../5.5/gcc_64/mkspecs/features/warn_on.prf \
		../../5.5/gcc_64/mkspecs/features/testcase_targets.prf \
		../../5.5/gcc_64/mkspecs/features/exceptions.prf \
		../../5.5/gcc_64/mkspecs/features/yacc.prf \
		../../5.5/gcc_64/mkspecs/features/lex.prf \
		epoll.pro
	$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile epoll.pro
../../5.5/gcc_64/mkspecs/features/spec_pre.prf:
../../5.5/gcc_64/mkspecs/common/unix.conf:
../../5.5/gcc_64/mkspecs/common/linux.conf:
../../5.5/gcc_64/mkspecs/common/sanitize.conf:
../../5.5/gcc_64/mkspecs/common/gcc-base.conf:
../../5.5/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../5.5/gcc_64/mkspecs/common/g++-base.conf:
../../5.5/gcc_64/mkspecs/common/g++-unix.conf:
../../5.5/gcc_64/mkspecs/qconfig.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_3dcollision.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_3dcollision_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../5.5/gcc_64/mkspecs/features/qt_functions.prf:
../../5.5/gcc_64/mkspecs/features/qt_config.prf:
../../5.5/gcc_64/mkspecs/linux-g++/qmake.conf:
../../5.5/gcc_64/mkspecs/features/spec_post.prf:
../../5.5/gcc_64/mkspecs/features/exclusive_builds.prf:
../../5.5/gcc_64/mkspecs/features/default_pre.prf:
../../5.5/gcc_64/mkspecs/features/resolve_config.prf:
../../5.5/gcc_64/mkspecs/features/default_post.prf:
../../5.5/gcc_64/mkspecs/features/c++11.prf:
../../5.5/gcc_64/mkspecs/features/warn_on.prf:
../../5.5/gcc_64/mkspecs/features/testcase_targets.prf:
../../5.5/gcc_64/mkspecs/features/exceptions.prf:
../../5.5/gcc_64/mkspecs/features/yacc.prf:
../../5.5/gcc_64/mkspecs/features/lex.prf:
epoll.pro:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile epoll.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

